language: java
script: gradle dist
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties
deploy:
  provider: releases
  api_key:
    secure: Uyx0s8cvlTwy1+hOQewpLUL4JZhF0H/YH4+fEARz7ejldNMdZZMzgbSlvaa/kEPoV4pRKVl9JIlPRToDv0e3xdycVeAN8t27FcjGax4rMJ4F9a6fuaCFRtDjSu757YgBj62C+2rNvDVkVYCoqTAtB409EqSXajZXQajxKUXKpn0=
  file:
    - build/distributions/xmlcalabash1-xmlunit-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
