language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: cUQJO634saTtszpZZNNl8t+9hnQho5snjVv6BPC8s+QcYB4FN7KPx9+MhDqdhKuDDC7UTSIfeWI4xCdjcOijO1YAiB0f0Gf52820C+yDwnOk+Fo916CG1FKzrTWzWRBgLpNcJrNWs6UpQpaKoTlqEqF2nkAP6Ud6dQrFTI+3YZY=
  file:
    - build/distributions/xmlcalabash1-xmlunit-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true


